# This file must NOT be committed with your personal keys

development:
  GOOGLE_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID'
  GOOGLE_SECRET_ID: 'YOUR_GOOGLE_SECRET_ID'
  FACEBOOK_CLIENT_ID: 'YOUR_FACEBOOK_CLIENT_ID'
  FACEBOOK_SECRET_ID: 'YOUR_FACEBOOK_SECRET_ID'
  TWITTER_CLIENT_ID: 'YOUR_TWITTER_CLIENT_ID'
  TWITTER_SECRET_ID: 'YOUR_TWITTER_SECRET_ID'
  GITHUB_CLIENT_ID: 'YOUR_GITHUB_CLIENT_ID'
  GITHUB_SECRET_ID: 'YOUR_GITHUB_SECRET_ID'
test:
  GOOGLE_CLIENT_ID: 'MY_GOOGLE_CLIENT_ID_FOR_TEST'
  GOOGLE_SECRET_ID: 'MY_GOOGLE_SECRET_ID_FOR_TEST'
  FACEBOOK_CLIENT_ID: 'MY_FACEBOOK_CLIENT_ID_FOR_TEST'
  FACEBOOK_SECRET_ID: 'MY_FACEBOOK_SECRET_ID_FOR_TEST'
  TWITTER_CLIENT_ID: 'MY_TWITTER_SECRET_ID_FOR_TEST'
  TWITTER_SECRET_ID: 'MY_TWITTER_SECRET_ID_FOR_TEST'
  GITHUB_CLIENT_ID: 'MY_GITHUB_SECRET_ID_FOR_TEST'
  GITHUB_SECRET_ID: 'MY_GITHUB_SECRET_ID_FOR_TEST'
